// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220613221522_AddCompanyId")]
    partial class AddCompanyId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Company 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Company 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Company 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Company 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Company 5"
                        });
                });

            modelBuilder.Entity("Models.Toys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Toys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 10,
                            CompanyId = 1,
                            Description = "Description toy 1",
                            Name = "Toy 1",
                            Price = 10m
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 10,
                            CompanyId = 2,
                            Description = "Description toy 2",
                            Name = "Toy 2",
                            Price = 20m
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 10,
                            CompanyId = 3,
                            Description = "Description toy 3",
                            Name = "Toy 3",
                            Price = 30m
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 10,
                            CompanyId = 4,
                            Description = "Description toy 4",
                            Name = "Toy 4",
                            Price = 40m
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = 10,
                            CompanyId = 5,
                            Description = "Description toy 5",
                            Name = "Toy 5",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("Models.Toys", b =>
                {
                    b.HasOne("Models.Company", "Company")
                        .WithMany("Toys")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Models.Company", b =>
                {
                    b.Navigation("Toys");
                });
#pragma warning restore 612, 618
        }
    }
}
